"""init: create all tables from scratch

Revision ID: 39f2080cc2ff
Revises: 
Create Date: 2025-12-06 18:56:02.947409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f2080cc2ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文件唯一ID'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='文件原始名称'),
    sa.Column('stored_name', sa.String(length=36), nullable=False, comment='存储用UUID文件名'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('hash', sa.String(length=64), nullable=True, comment='文件SHA256哈希'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='文件MIME类型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_codes',
    sa.Column('code', sa.String(length=6), nullable=False, comment='6位取件码（大写字母+数字）'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='关联文件ID'),
    sa.Column('status', sa.Enum('waiting', 'transferring', 'completed', 'expired'), nullable=True, comment='取件码状态'),
    sa.Column('used_count', sa.Integer(), nullable=True, comment='已使用次数'),
    sa.Column('limit_count', sa.Integer(), nullable=True, comment='最大使用次数（999=无限）'),
    sa.Column('uploader_ip', sa.String(length=45), nullable=True, comment='上传者IP'),
    sa.Column('expire_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='举报ID'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='关联取件码'),
    sa.Column('reason', sa.Text(), nullable=False, comment='举报原因'),
    sa.Column('reporter_ip', sa.String(length=45), nullable=True, comment='举报者IP'),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'resolved'), nullable=True, comment='举报处理状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['code'], ['pickup_codes.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webrtc_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='关联取件码'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='WebRTC会话唯一标识'),
    sa.Column('offer', sa.Text(), nullable=True, comment='SDP Offer（分享方生成）'),
    sa.Column('answer', sa.Text(), nullable=True, comment='SDP Answer（领取方生成）'),
    sa.Column('ice_candidates', sa.JSON(), nullable=True, comment='ICE候选列表（MySQL5.7+）'),
    sa.Column('status', sa.Enum('pending', 'offer_created', 'answer_received', 'connected', 'failed', 'closed'), nullable=True, comment='会话状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['code'], ['pickup_codes.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'session_id', name='uk_code_session')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webrtc_sessions')
    op.drop_table('reports')
    op.drop_table('pickup_codes')
    op.drop_table('files')
    # ### end Alembic commands ###
