"""用户表关联上传表和举报表

Revision ID: 3f743ea0a4ee
Revises: 5c23457abcc0
Create Date: 2026-01-04 20:18:03.452043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f743ea0a4ee'
down_revision: Union[str, Sequence[str], None] = '5c23457abcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_codes', sa.Column('user_id', sa.Integer(), nullable=True, comment='上传者用户ID（可选）'))
    op.create_foreign_key(None, 'pickup_codes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True, comment='举报者用户ID（可选）'))
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    op.drop_constraint(None, 'pickup_codes', type_='foreignkey')
    op.drop_column('pickup_codes', 'user_id')
    # ### end Alembic commands ###
