"""user用户表

Revision ID: 5c23457abcc0
Revises: 606a1b8580df
Create Date: 2026-01-04 20:16:20.059174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c23457abcc0'
down_revision: Union[str, Sequence[str], None] = '606a1b8580df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名（唯一）'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='密码哈希（不存储明文）'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱（唯一，可选）'),
    sa.Column('role', sa.Enum('user', 'admin'), nullable=True, comment='用户角色（普通用户/管理员）'),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned'), nullable=True, comment='账号状态'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录IP'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
