"""Add registered_senders table

Revision ID: 82fcfd6a238f
Revises: 39f2080cc2ff
Create Date: 2025-12-25 22:13:47.232050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fcfd6a238f'
down_revision: Union[str, Sequence[str], None] = '39f2080cc2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_senders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('sender_info', sa.JSON(), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'notified', 'expired', name='sender_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['code'], ['pickup_codes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registered_senders')
    # ### end Alembic commands ###
