"""新的表

Revision ID: ee3bf6ad5311
Revises: 82fcfd6a238f
Create Date: 2026-01-01 23:49:47.410376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3bf6ad5311'
down_revision: Union[str, Sequence[str], None] = '82fcfd6a238f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_storages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='存储记录ID'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='关联文件ID'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='文件在服务器的存储路径'),
    sa.Column('storage_node', sa.String(length=100), nullable=True, comment='存储节点标识（如多服务器部署时）'),
    sa.Column('is_valid', sa.Boolean(), nullable=True, comment='存储文件是否有效'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='传输记录ID'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='关联取件码'),
    sa.Column('receiver_ip', sa.String(length=45), nullable=True, comment='接收者IP'),
    sa.Column('status', sa.Enum('pending', 'transferring', 'completed', 'failed'), nullable=True, comment='传输状态：等待中/传输中/完成/失败'),
    sa.Column('progress', sa.Float(), nullable=True, comment='传输进度（0.0-100.0）'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='传输完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['code'], ['pickup_codes.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='上传记录ID'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='关联文件ID'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='关联取件码（上传时绑定的取件码）'),
    sa.Column('uploader_ip', sa.String(length=45), nullable=True, comment='上传者IP地址'),
    sa.Column('status', sa.Enum('pending', 'uploading', 'completed', 'failed'), nullable=True, comment='上传状态：等待中/上传中/完成/失败'),
    sa.Column('progress', sa.Float(), nullable=True, comment='上传进度（0.0-100.0）'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='上传失败时的错误信息'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='上传完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['code'], ['pickup_codes.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    op.drop_table('file_transfers')
    op.drop_table('file_storages')
    # ### end Alembic commands ###
