"""我创建了数据库，对齐了user.py文件里的user表

Revision ID: 89d47b535be1
Revises: 
Create Date: 2025-11-15 12:10:27.395014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89d47b535be1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_receiver_records'), table_name='transfer_record')
    op.drop_index(op.f('idx_session_completed'), table_name='transfer_record')
    op.drop_table('transfer_record')
    op.drop_index(op.f('idx_access_password'), table_name='share_session')
    op.drop_index(op.f('idx_status_expire'), table_name='share_session')
    op.drop_table('share_session')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=False, comment='用户唯一标识（UUID）'),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True, comment='用户名（非必填）'),
    sa.Column('login_account', mysql.VARCHAR(length=100), nullable=True, comment='登录账号（唯一）'),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True, comment='登录密码哈希值'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='存储用户基础信息',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='存储用户基础信息',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('share_session',
    sa.Column('session_id', mysql.VARCHAR(length=50), nullable=False, comment='传输会话唯一ID（UUID）'),
    sa.Column('sharer_id', mysql.VARCHAR(length=50), nullable=False, comment='分享者ID（关联用户表）'),
    sa.Column('max_share_count', mysql.INTEGER(), autoincrement=False, nullable=False, comment='最大分享人数'),
    sa.Column('time_limit', mysql.INTEGER(), autoincrement=False, nullable=False, comment='分享时间限制（分钟，0表示无限制）'),
    sa.Column('access_password', mysql.VARCHAR(length=50), nullable=False, comment='分享码（加密存储）'),
    sa.Column('sharer_sdp_offer', mysql.TEXT(), nullable=True, comment='分享者SDP Offer'),
    sa.Column('sharer_ip', mysql.VARCHAR(length=50), nullable=True, comment='分享者IP地址'),
    sa.Column('sharer_port', mysql.INTEGER(), autoincrement=False, nullable=True, comment='分享者端口号'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='会话创建时间'),
    sa.Column('expire_time', mysql.DATETIME(), nullable=True, comment='会话过期时间'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='会话状态（1-有效，0-已过期/关闭）'),
    sa.ForeignKeyConstraint(['sharer_id'], ['user.user_id'], name='fk_share_session_sharer', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    comment='存储分享会话核心配置',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='存储分享会话核心配置',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_status_expire'), 'share_session', ['status', 'expire_time'], unique=False)
    op.create_index(op.f('idx_access_password'), 'share_session', ['access_password'], unique=False)
    op.create_table('transfer_record',
    sa.Column('record_id', mysql.VARCHAR(length=50), nullable=False, comment='传输记录唯一标识（UUID）'),
    sa.Column('session_id', mysql.VARCHAR(length=50), nullable=False, comment='关联会话ID'),
    sa.Column('sharer_id', mysql.VARCHAR(length=50), nullable=False, comment='分享者ID'),
    sa.Column('receiver_id', mysql.VARCHAR(length=50), nullable=False, comment='接收者ID'),
    sa.Column('receiver_sdp_answer', mysql.TEXT(), nullable=True, comment='接收者SDP Answer'),
    sa.Column('receiver_ip', mysql.VARCHAR(length=50), nullable=True, comment='接收者IP地址'),
    sa.Column('receiver_port', mysql.INTEGER(), autoincrement=False, nullable=True, comment='接收者端口号'),
    sa.Column('is_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否传输完成（1-完成，0-未完成）'),
    sa.Column('transfer_size', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='已传输字节数'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.user_id'], name=op.f('fk_transfer_receiver'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['share_session.session_id'], name=op.f('fk_transfer_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sharer_id'], ['user.user_id'], name=op.f('fk_transfer_sharer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    comment='记录传输详细信息',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='记录传输详细信息',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_session_completed'), 'transfer_record', ['session_id', 'is_completed'], unique=False)
    op.create_index(op.f('idx_receiver_records'), 'transfer_record', ['receiver_id', 'is_completed'], unique=False)
    # ### end Alembic commands ###
