"""Initial migration

Revision ID: dd7cf029d02e
Revises: 89d47b535be1
Create Date: 2025-11-22 18:34:39.486175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7cf029d02e'
down_revision: Union[str, Sequence[str], None] = '89d47b535be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_session',
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='传输会话唯一ID（UUID）'),
    sa.Column('sharer_id', sa.String(length=50), nullable=False, comment='分享者ID（关联用户表）'),
    sa.Column('max_share_count', sa.Integer(), nullable=False, comment='最大分享人数'),
    sa.Column('time_limit', sa.Integer(), nullable=False, comment='分享时间限制（分钟，0表示无限制）'),
    sa.Column('access_password', sa.String(length=50), nullable=False, comment='分享码（加密存储）'),
    sa.Column('sharer_sdp_offer', sa.String(length=255), nullable=True, comment='分享者SDP Offer'),
    sa.Column('sharer_ip', sa.String(length=50), nullable=True, comment='分享者IP地址'),
    sa.Column('sharer_port', sa.Integer(), nullable=True, comment='分享者端口号'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='会话创建时间'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='会话过期时间'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='会话状态（1-有效，0-已过期/关闭）'),
    sa.ForeignKeyConstraint(['sharer_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('file_info',
    sa.Column('file_id', sa.String(length=50), nullable=False, comment='文件唯一标识（UUID）'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='关联会话ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件原始名称'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('file_hash', sa.String(length=100), nullable=True, comment='文件哈希值（校验完整性）'),
    sa.ForeignKeyConstraint(['session_id'], ['share_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('transfer_record',
    sa.Column('record_id', sa.String(length=50), nullable=False, comment='传输记录唯一标识（UUID）'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='关联会话ID'),
    sa.Column('sharer_id', sa.String(length=50), nullable=False, comment='分享者ID'),
    sa.Column('receiver_id', sa.String(length=50), nullable=False, comment='接收者ID'),
    sa.Column('receiver_sdp_answer', sa.Text(), nullable=True, comment='接收者SDP Answer'),
    sa.Column('receiver_ip', sa.String(length=50), nullable=True, comment='接收者IP地址'),
    sa.Column('receiver_port', sa.Integer(), nullable=True, comment='接收者端口号'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='是否传输完成（1-完成，0-未完成）'),
    sa.Column('transfer_size', sa.BigInteger(), nullable=True, comment='已传输字节数'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['share_session.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sharer_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_record')
    op.drop_table('file_info')
    op.drop_table('share_session')
    # ### end Alembic commands ###
